# Generated by Django 5.1.3 on 2025-03-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tanggal_pesan',
            new_name='tanggal_pesanan',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='jumlah',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='nama_menu',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='metode_pembayaran',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='nama_pemesan',
            field=models.CharField(max_length=100),
        ),
    ]
