# Generated by Django 5.1.3 on 2025-03-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0002_rename_tanggal_pesan_order_tanggal_pesanan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
