# Generated by Django 5.1.3 on 2025-03-15 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0005_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_meja', models.CharField(max_length=10)),
                ('nama_pemesan', models.CharField(max_length=255)),
                ('tanggal_pemesanan', models.DateTimeField(default=django.utils.timezone.now)),
                ('jenis_pembayaran', models.CharField(max_length=50)),
                ('total_harga', models.IntegerField()),
                ('detail_pesanan', models.TextField()),
            ],
        ),
    ]
