# Generated by Django 5.1.3 on 2025-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0006_customerorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bill', models.CharField(default='5E6590D725', max_length=10, unique=True)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('no_meja', models.CharField(max_length=10)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('metode_pembayaran', models.CharField(choices=[('transfer', 'Transfer Bank'), ('tunai', 'Tunai')], max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('makanan_1', models.CharField(blank=True, max_length=100, null=True)),
                ('makanan_2', models.CharField(blank=True, max_length=100, null=True)),
                ('minuman_1', models.CharField(blank=True, max_length=100, null=True)),
                ('minuman_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
