# Generated by Django 5.1.3 on 2025-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0007_customer_delete_customerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kode_bill',
            field=models.CharField(default='66A26B99C8', max_length=10, unique=True),
        ),
    ]
