# Generated by Django 5.1.3 on 2025-03-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0008_alter_customer_kode_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
