# Generated by Django 5.1.3 on 2025-03-15 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0009_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bill', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('no_meja', models.CharField(max_length=10)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('metode_pembayaran', models.CharField(choices=[('transfer', 'Transfer Bank'), ('tunai', 'Tunai')], max_length=50)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_ERP.customerorder')),
            ],
        ),
    ]
