# Generated by Django 5.1.3 on 2025-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0011_remove_orderitem_order_delete_customerorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bill', models.CharField(max_length=10, unique=True)),
                ('nama_pemesan', models.CharField(max_length=255)),
                ('no_meja', models.CharField(max_length=10)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('total_harga', models.IntegerField()),
                ('menu_pesanan', models.TextField()),
            ],
        ),
    ]
