# Generated by Django 5.1.3 on 2025-03-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='metode_pembayaran',
            new_name='jenis_pembayaran',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_pesanan',
        ),
        migrations.AlterField(
            model_name='order',
            name='kode_bill',
            field=models.CharField(default='FA5881E993', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('jumlah', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_ERP.order')),
            ],
        ),
    ]
