# Generated by Django 5.1.3 on 2025-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0013_rename_metode_pembayaran_order_jenis_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kode_bill',
            field=models.CharField(default='6DA68BD30A', max_length=10, unique=True),
        ),
    ]
