# Generated by Django 5.1.3 on 2025-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0016_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_code',
            field=models.CharField(default='99eec4add6', max_length=10, unique=True),
        ),
    ]
