# Generated by Django 5.1.3 on 2025-03-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0017_alter_order_bill_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
