# Generated by Django 5.1.3 on 2025-03-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0019_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
