# Generated by Django 5.1.3 on 2025-03-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0020_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('no_meja', models.CharField(max_length=10)),
                ('metode_pembayaran', models.CharField(max_length=20)),
                ('total_harga', models.IntegerField()),
                ('tanggal_pesanan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_ERP.order')),
            ],
        ),
    ]
