# Generated by Django 5.1.3 on 2025-03-15 21:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0021_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kode_bill',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
