# Generated by Django 5.1.3 on 2025-03-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0022_order_kode_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kode_bill',
        ),
    ]
