# Generated by Django 5.1.3 on 2025-03-15 22:14

import App_ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0023_remove_order_kode_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kode_bill',
            field=models.CharField(default=App_ERP.models.generate_kode_bill, max_length=8, unique=True),
        ),
    ]
