# Generated by Django 5.1.4 on 2025-04-14 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0024_order_kode_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('inventori', 'Admin Inventori'), ('produksi', 'Admin Manajemen Produksi & Stok'), ('pos', 'Admin POS'), ('keuangan', 'Admin Keuangan'), ('crm', 'Admin CRM'), ('hrd', 'Admin HRD')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
