# Generated by Django 5.1.4 on 2025-04-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0026_orderitem_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
    ]
