# Generated by Django 5.1.4 on 2025-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0028_orderitem_menu_rating_servicerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
