# Generated by Django 5.1.4 on 2025-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0029_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('total_kehadiran', models.IntegerField()),
                ('total_izin', models.IntegerField()),
                ('total_alpha', models.IntegerField()),
            ],
        ),
    ]
