# Generated by Django 5.1.4 on 2025-05-02 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0030_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_stock', models.PositiveIntegerField(default=50)),
                ('remaining_stock', models.PositiveIntegerField(default=50)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='App_ERP.menuitem')),
            ],
        ),
    ]
