# Generated by Django 5.1.4 on 2025-05-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0031_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
