# Generated by Django 5.2 on 2025-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0032_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='lembur_jam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='total_gaji',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
