# Generated by Django 5.2 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0033_karyawan_lembur_jam_karyawan_total_gaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
