# Generated by Django 5.1.4 on 2025-05-05 20:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0034_karyawan_tanggal_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='tanggal_masuk',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='FoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stock_in', models.PositiveIntegerField(default=50)),
                ('stock_out', models.PositiveIntegerField(default=0)),
                ('remaining_stock', models.PositiveIntegerField(default=50)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ERP.menuitem')),
            ],
        ),
    ]
