# Generated by Django 5.2 on 2025-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0035_alter_karyawan_tanggal_masuk_foodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='gaji_pokok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tunjangan_jabatan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
