# Generated by Django 5.2 on 2025-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0036_karyawan_gaji_pokok_karyawan_tunjangan_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(choices=[('A', 'Divisi A'), ('B', 'Divisi B'), ('C', 'Divisi C'), ('D', 'Divisi D')], default='A', max_length=1),
        ),
    ]
