# Generated by Django 5.2 on 2025-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0037_karyawan_divisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='alamat',
            field=models.CharField(default='Belum diisi', max_length=255),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='j_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=20),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='kontak',
            field=models.CharField(default='Belum diisi', max_length=20),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='no_rekening',
            field=models.CharField(default='Belum diisi', max_length=50),
        ),
    ]
