# Generated by Django 5.2 on 2025-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0038_karyawan_alamat_karyawan_j_kelamin_karyawan_kontak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='j_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
