# Generated by Django 5.2 on 2025-05-19 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ERP', '0039_alter_karyawan_j_kelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokBahanBaku',
            fields=[
                ('kode_bahan_baku', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_bahan', models.CharField(max_length=100)),
                ('harga_per_unit', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stok_minimum', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('supplier', models.CharField(max_length=100)),
                ('tanggal_kadaluarsa', models.DateField()),
                ('jumlah', models.IntegerField(default=0)),
                ('lokasi', models.CharField(default='Gudang A', max_length=50)),
                ('tanggal_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodstock',
            name='status',
            field=models.CharField(default='Tersedia', max_length=100),
        ),
        migrations.CreateModel(
            name='TransaksiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ERP.stokbahanbaku')),
            ],
        ),
    ]
